'''
    Initial example generated by GPT-3.5
'''

# Example: Evaluating if a student is eligible for a programming competition

# Taking user input
student_age = int(input("Enter the student's age: "))
has_parental_permission = input("Does the student have parental permission? (yes/no): ").lower() == "yes"
is_registered = input("Is the student registered? (yes/no): ").lower() == "yes"

# Relational operators
is_old_enough = student_age >= 16
is_young_enough = student_age <= 18

# Logical operators
can_participate = (is_old_enough and is_young_enough) and (has_parental_permission or is_registered)
cannot_participate = not can_participate

# Displaying the results
print("Student Age:", student_age)
print("Has Parental Permission:", has_parental_permission)
print("Is Registered:", is_registered)
print("Is Old Enough:", is_old_enough)
print("Is Young Enough:", is_young_enough)
print("Can Participate:", can_participate)
print("Cannot Participate:", cannot_participate)

if can_participate:
    print("The student is eligible to participate in the programming competition!")
else:
    print("The student is not eligible to participate in the programming competition.")